### PR TITLE
Implement MikroTik Winbox Plugin

### PR DESCRIPTION
**Pull request by Lillecarl**
Implements support for MikroTik WinBox connections within Terminals in "the same" way as Putty is implemented. 👍

### CODE REVIEW

**Comment by Lillecarl** [comment]
https://www.youtube.com/watch?v=5RTwsErKgSI

**Comment by Lillecarl** [comment]
Should probably be some test for this, but idk how to write those =)

**Comment by jirkapok** [comment]
Here we have two things to consider:
1. Should this kind of connection be provided out of the box or not?
* Yes - than we need integration tests, probably with some docker environment, when possible (see Resources\TestData\DockerLab\ directory). Because we are currently overloaded with testing of currently supported protocols. I have no experience with the Winbox tool.
* NO - i am fine, if we add this as separate repository, with isolated release cycle under your control and extend our user documentation pointing to your plugin download page.

**Comment by Lillecarl** [comment]
1. I'd say getting this into master would give us a good advantage on mRemoteNG, but to me personally there's no need getting there right now, as long as we can merge the terminals.common changes =)
2. I could host a MikroTik router on Amazon AWS, and add a readonly user to those tests
3. See 2, it's a fairly simple tool.

**Comment by jirkapok** [comment]
What about licensing. Did you check, if it is posible to deploy WinBox as part of another application?

**Comment by Lillecarl** [comment]
I'm honestly not sure about their redistribution terms, they can't be too strict considering i automatically publish WinBox if i open the WebUI to WAN.

If it would be an issue one could make the downloader install it instead.

**Comment by jirkapok** [comment]
Considering no body is against, i will merge, when other features are finished.

**Comment by Lillecarl** [comment]
@jirkapok What other features are we talking about, is there anything i cal help out with? I'm eager to get winbox and http form filling into terminals, then we can start deploying it at work to our techs.

And i don't wanna maintain a custom Terminals version, i'd rather see all nice features upstream :)

**Comment by jirkapok** [comment]
Please provide all kind of tests, like the other plugins have.

**Comment by Lillecarl** [comment]
I won't be able to do this, i don't fully understand the installer. I'll leave this here if someone want's to pick it up at some point. I should be able to provide similar tests to Putty at some point though.

**Comment by wolfen351** [comment]
Wow this is a great addition to Terminals, just wanted to voice my support for this feature, it will come in really handy

**Pull request closed without merging**
