### PR TITLE
Vnc session crashes if click non-client area

### PR DESCRIPTION
**Pull request by takuya-takeuchi**
Fix:
- VNC session always crashes if user click non-client screen area; black screen.

### CODE REVIEW

**Comment by jirkapok** [comment]
Thanks very much for contribution. The only question is, how to get such changes to original VncSharp source, so we dont have to compile our own version.

**Comment by jbowtie** [comment]
@takuya-takeuchi Could you add a pull request upstream to https://github.com/humphd/VncSharp as well? That should allow @jirkapok to discuss with the upstream maintainer about if/when the fix can be released.

**Comment by takuya-takeuchi** [comment]
I'm so sorry for my delay response.

> Could you add a pull request upstream to https://github.com/humphd/VncSharp as well?

Does it mean that I do the following command in folked Terminal local repo?
I am not sure whether my understand is correct.
    
    git remote add upstream https://github.com/humphd/VncSharp

Thank you for your cooperations.

**Comment by jbowtie** [comment]
@takuya-takeuchi I meant please fork the VncSharp repo and submit the same fix there.

**Comment by jirkapok** [comment]
Yes, please create pull request also into the VncSharp, i am not sure how much our version is compatible with original project.

**Comment by jirkapok** [comment]
Pull request to original repo is not needed, since there is exact line match.

**Pull request merged**
