### PR TITLE
Add masterpassword commandline argument

### PR DESCRIPTION
**Pull request by limaolm**
Add master password commandline argument to provide master password from commandline. This is useful for launching terminals from scripts.

### CODE REVIEW

**Comment by jirkapok** [comment]
Thank you for your proposal, but this already has been discussed and for security reasons nobody implemented. The issue here is, that using master password as command line argument publishes the password in plain text, since command line arguments can be obtained by any user as a property of running process. Use empty password instead, if security isnt an issue for you.

**Comment by limaolm** [comment]
"The issue here is, that using master password as command line argument publishes the password in plain text, since command line arguments can be obtained by any user as a property of running process. ". Good point, I agree!

However, if we use empty master password, seems encrypted password saved in the Favorites.xml could not be loaded from other machines. Security and usability is always hard to coordinate:)

**Comment by jirkapok** [comment]
Please prose the first commit as a separate pull request to upgrade to .net 4.6.1.

**Comment by limaolm** [comment]
I upgraded its dependency to .net 4.6.1 to leverage the async/await feature. And for my own using scenario(I found opening multiple connections(different logon account) to a single RDP machine at the same time will fail occasionally), I added 2000ms interval between opening each connection, when right click a favorite folder to open multiple connections. I am not sure this change is acceptable for other Terminals users. If yes, I can create another pull request for it. If not, please abandon this pull request:)

**Comment by jirkapok** [comment]
please extract all the mentioned changes (.net upgrade, delay in connection, commandline argument) as separate pull requests.

**Pull request closed without merging**
